### ISSUE TITLE
kubedev login

### ISSUE THREAD

**Issue by fabiandeifuss** [daniel-kun/kubedev#2]
When pushing to a **private container registry** I have to manually login for each CI pipeline. An integration in the name of standardization is desired.

A command like `kubedev login` could look for a number of required environment variables:

    CONTAINER_REGISTRY            your private registry
    CONTAINER_REGISTRY_PASSWORD   your password to access the registry
    CONTAINER_ENGINE              podman / docker / ...

To finally carry out the login:

```
CONTAINER_REGISTRY=xyz CONTAINER_REGISTRY_PASSWORD=abc CONTAINER_ENGINE=podman kubedev login
```

**Comment by daniel-kun** [comment]
This has been solved by using `DOCKER_AUTH_CONFIG`, which will be written to ~/.docker/config.json under certain conditions.
